Repository oacore/design, pull requests merged in 2020-07, with the labels that each got.

#207 Add flex layout to the FormGroup
  src/elements/forms/styles.css
Labels: 🎨 css

#212 Fix React warnings
  src/elements/detail-list/detail-list.md
  src/elements/forms/text-field.md
  src/elements/icon/icon.md
  src/elements/table/table.md
  styleguide.config.js
Labels: bug

#215 Add README.md
  README.md
Labels: help wanted

#217 Add CORE logo component
  assets/core-symbol.svg
  design.config.js
  src/elements/index.css
  src/elements/index.js
  src/elements/logo/index.js
  src/elements/logo/logo.css
  src/elements/logo/logo.jsx
  src/elements/logo/logo.md
Labels: ⚛️ components

#223 Optimise spinner animation
  src/elements/progress-spinner/styles.css
Labels: bug, 🎨 css

#237 Fix searchForm param
  bin/config.js
Labels: bug
